{
  "_comment": "GENERADO POR theme/apply.sh desde theme/palette.sh — NO EDITAR",
  "name": "Catppuccin Mocha",
  "base": "dark",
  "overrides": {
    "claude": "{{ SECONDARY }}",
    "claudeShimmer": "{{ SECONDARY|mix FG 35% }}",
    "text": "{{ FG }}",
    "inverseText": "{{ BG }}",
    "inactive": "{{ FG|mix BG 40% }}",
    "inactiveShimmer": "{{ FG|mix BG 25% }}",
    "subtle": "{{ MUTED }}",
    "suggestion": "{{ TEAL }}",
    "permission": "{{ BLUE }}",
    "permissionShimmer": "{{ BLUE|mix FG 35% }}",
    "remember": "{{ YELLOW }}",
    "success": "{{ GREEN }}",
    "error": "{{ RED }}",
    "warning": "{{ YELLOW }}",
    "warningShimmer": "{{ YELLOW|mix FG 35% }}",
    "merged": "{{ PINK }}",
    "promptBorder": "{{ ACCENT }}",
    "promptBorderShimmer": "{{ ACCENT|mix FG 35% }}",
    "planMode": "{{ TEAL }}",
    "autoAccept": "{{ YELLOW }}",
    "bashBorder": "{{ PEACH }}",
    "ide": "{{ SKY }}",
    "diffAdded": "{{ BG|mix GREEN 15% }}",
    "diffRemoved": "{{ BG|mix RED 15% }}",
    "diffAddedDimmed": "{{ BG|mix GREEN 8% }}",
    "diffRemovedDimmed": "{{ BG|mix RED 8% }}",
    "diffAddedWord": "{{ BG|mix GREEN 32% }}",
    "diffRemovedWord": "{{ BG|mix RED 32% }}",
    "userMessageBackground": "{{ BG|mix FG 6% }}",
    "userMessageBackgroundHover": "{{ BG|mix FG 10% }}",
    "bashMessageBackgroundColor": "{{ BG|mix FG 6% }}",
    "memoryBackgroundColor": "{{ BG|mix FG 6% }}",
    "selectionBg": "{{ SELECTION }}",
    "rate_limit_fill": "{{ ACCENT }}",
    "rate_limit_empty": "{{ BG|mix FG 20% }}",
    "briefLabelYou": "{{ YELLOW }}",
    "briefLabelClaude": "{{ SECONDARY }}"
  }
}
